site_name: Nuru Clock Documentation
site_url: https://ktrain5369.me/neuro-i18nd-clock

theme: 
  name: material
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KTrain5169
    - icon: fontawesome/brands/discord
      link: https://discord.gg/G6YvWhctjk
    - icon: fontawesome/brands/bluesky
      link: https://bsky.social/profile/ktrain5369.me

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search